version: '3'

services:
  db:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./volumes/contacts_db:/contacts_db
    environment:
      POSTGRES_USER: contacts_db
      POSTGRES_PASSWORD: contacts_db_pass
      POSTGRES_DB: contacts_db
      PGDATA: /contacts_db
  api:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: contacts_db
      POSTGRES_PASSWORD: contacts_db_pass
      POSTGRES_DB: contacts_db